-- =============================================================================
-- 99_cleanup.sql
-- Remove demo2 objects from TSHO_SWT_TOKYO_26 ONLY
-- Does NOT touch FRAUD_DEMO database or any other database
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- Agent + Semantic View (AI schema)
DROP AGENT IF EXISTS TSHO_SWT_TOKYO_26.AI.FRAUD_INVESTIGATOR;
DROP SEMANTIC VIEW IF EXISTS TSHO_SWT_TOKYO_26.AI.SV_FRAUD_SCORES;

-- Cortex Search
DROP CORTEX SEARCH SERVICE IF EXISTS TSHO_SWT_TOKYO_26.FRAUD.FRAUD_POLICY_SEARCH;

-- Views
DROP VIEW IF EXISTS TSHO_SWT_TOKYO_26.FRAUD.FRAUD_SCORES_ENRICHED;
DROP VIEW IF EXISTS TSHO_SWT_TOKYO_26.FRAUD.PREDICTION_LOG_WITH_BASELINE;
DROP VIEW IF EXISTS TSHO_SWT_TOKYO_26.FRAUD.DRIFT_DAILY_SUMMARY;

-- Tables
DROP TABLE IF EXISTS TSHO_SWT_TOKYO_26.FRAUD.FRAUD_SCORES;
DROP TABLE IF EXISTS TSHO_SWT_TOKYO_26.FRAUD.PREDICTION_LOG;
DROP TABLE IF EXISTS TSHO_SWT_TOKYO_26.FRAUD.POLICY_DOCUMENTS;
DROP TABLE IF EXISTS TSHO_SWT_TOKYO_26.FRAUD_ML.TRAINING_DATASET;

-- Dynamic Table
DROP DYNAMIC TABLE IF EXISTS TSHO_SWT_TOKYO_26.FRAUD.FRAUD_FEATURES;

-- Raw tables
DROP TABLE IF EXISTS TSHO_SWT_TOKYO_26.FRAUD.RAW_TRANSACTIONS;
DROP TABLE IF EXISTS TSHO_SWT_TOKYO_26.FRAUD.RAW_CUSTOMER_PROFILES;
DROP TABLE IF EXISTS TSHO_SWT_TOKYO_26.FRAUD.RAW_MERCHANT_PROFILES;

-- Stages
DROP STAGE IF EXISTS TSHO_SWT_TOKYO_26.FRAUD.DATA_STAGE;
DROP STAGE IF EXISTS TSHO_SWT_TOKYO_26.FRAUD.AGENT_DOCS_STAGE;

-- Schemas (only demo2-specific, within TSHO_SWT_TOKYO_26)
DROP SCHEMA IF EXISTS TSHO_SWT_TOKYO_26.FRAUD;
DROP SCHEMA IF EXISTS TSHO_SWT_TOKYO_26.FRAUD_ML;

-- NOTE: Does NOT drop TSHO_SWT_TOKYO_26 database (shared with demo1)
-- NOTE: Does NOT drop any warehouse (TSHO_WH_XL, FRAUD_DEMO_ADAPTIVE_WH are shared/reusable)
-- NOTE: Does NOT drop any role
-- NOTE: Does NOT touch FRAUD_DEMO database or any other database
